// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKPM.Data;

namespace TKPM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220528033120_initDatabaseAndCreateDaiLyTable")]
    partial class initDatabaseAndCreateDaiLyTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TKPM.Models.DaiLy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoaiDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiDaiLy")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiQuanLy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NoDau")
                        .HasColumnType("int");

                    b.Property<int>("PhatSinh")
                        .HasColumnType("int");

                    b.Property<string>("QuanDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DaiLys");
                });
#pragma warning restore 612, 618
        }
    }
}
