// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKPM.Data;

namespace TKPM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220530030147_add-talbe")]
    partial class addtalbe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TKPM.Models.ChiTietXuatHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HangHoaId")
                        .HasColumnType("int");

                    b.Property<int>("PhieuXuatHangId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HangHoaId");

                    b.HasIndex("PhieuXuatHangId");

                    b.ToTable("ChiTietXuatHangs");
                });

            modelBuilder.Entity("TKPM.Models.DaiLy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChiDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoaiDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiDaiLy")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiQuanLy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NoDau")
                        .HasColumnType("int");

                    b.Property<int>("PhatSinh")
                        .HasColumnType("int");

                    b.Property<string>("QuanDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDaiLy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DaiLys");
                });

            modelBuilder.Entity("TKPM.Models.HangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("DonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTrongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("TKPM.Models.PhieuXuatHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DaiLyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapPhieuXuatHang")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DaiLyId");

                    b.ToTable("PhieuXuatHangs");
                });

            modelBuilder.Entity("TKPM.Models.ChiTietXuatHang", b =>
                {
                    b.HasOne("TKPM.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("HangHoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TKPM.Models.PhieuXuatHang", "PhieuXuatHang")
                        .WithMany("ChiTietXuatHangs")
                        .HasForeignKey("PhieuXuatHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("PhieuXuatHang");
                });

            modelBuilder.Entity("TKPM.Models.PhieuXuatHang", b =>
                {
                    b.HasOne("TKPM.Models.DaiLy", "DaiLy")
                        .WithMany()
                        .HasForeignKey("DaiLyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiLy");
                });

            modelBuilder.Entity("TKPM.Models.PhieuXuatHang", b =>
                {
                    b.Navigation("ChiTietXuatHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
